{
  "score": 84.0,
  "tests": [
    {
      "test": 1,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 2,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 3,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 4,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 5,
      "result": "no Out[N] output found for cell (note: printing the output does not work)",
      "weight": 1
    },
    {
      "test": 6,
      "result": "no plot found",
      "weight": 1
    },
    {
      "test": 7,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 8,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 9,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 10,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 11,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 12,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 13,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 14,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 15,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 16,
      "result": "not found",
      "weight": 1
    },
    {
      "test": 17,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 18,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 19,
      "result": "PASS",
      "weight": 1
    },
    {
      "test": 20,
      "result": "PASS",
      "weight": 1
    }
  ],
  "lint": [
    "cell: 10, line: 15 - Too broad exception clause. You should try catching specific exceptions"
  ],
  "date": "02/18/2020"
}